### ISSUE TITLE
Problem with Controller Input mapping on more then one Bluetooth Controller (PS3)

### ISSUE THREAD

**Issue by Linkinsoldier** [kodi-game/game.libretro.snes9x2002#2]
Preconditions:

1) Pair (Bluetooth!) Controller 1 and Controller 2 to Rpi3 (Kodi19 Milhouse Testbuild#205 )
2) Restart Rpi with NO Controller connected!
3) Now use PS Button to connect the old controller 2 as controller 1 --> Player 1 is displayed on PS3 Controller
4) Start Super Mario Allstars with Pocketsnes/snes9x2002 Emulator
5) Start Game Super Mario 1985 (Twice press Start)
6) Select 1 Player Game (via Start)

Excpected behaviour: 
Playing game is possible with this controller (old controller 2 mapped as controller 1)

Seen behaviour:
Controller 1 (old 2) is able to start game but not control Mario (character) in game
After activating Controller 2 (old 1) - which was deactivated before!!!! - character can be controller with controller 2 (old 1) but not with Controller 1 (old 2)

Remark: interesting enough the Controller 1 (old 2) works without issues on other games with the same emulator (e.g. NBA hang time!)

[kodi.zip](https://github.com/kodi-game/game.libretro.snes9x2002/files/784949/kodi.zip)

See attached log for more details

**Comment by Linkinsoldier** [comment]
Try#2 attaching the zip file:
[kodi.zip](https://github.com/kodi-game/game.libretro.snes9x2002/files/784945/kodi.zip)

**Comment by garbear** [comment]
Thanks for the awesome bug report! I've added this to my list of [controller bugs](https://github.com/garbear/xbmc/issues/79). I've already got 3 bugs in the queue, so it may be a week or two before I'm able to look into this.

**Comment by garbear** [comment]
Reported fixed in the forum.
